//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KronalUtils.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KronalUtils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shader &quot;Hidden/SlinDev/Desktop/PostProcessing/FXAA&quot;
        ///{
        ///	Properties
        ///	{
        ///		_MainTex (&quot;Base (RGB)&quot;, RECT) = &quot;white&quot; {}
        ///	}
        ///
        ///	SubShader
        ///	{
        ///		Pass
        ///		{
        ///			ZTest Always
        ///			Cull Off
        ///			ZWrite Off
        ///			Fog { Mode off }
        ///	
        ///			CGPROGRAM
        ///				#pragma target 3.0
        ///				#pragma glsl
        ///				#pragma vertex vert
        ///				#pragma fragment frag
        ///				#pragma fragmentoption ARB_precision_hint_fastest 
        ///				#include &quot;UnityCG.cginc&quot;
        ///				
        ///				uniform sampler2D _MainTex;
        ///				uniform float4 _MainTex_TexelSize;
        ///				
        ///				struct v2f
        ///				{
        ///					float4 pos  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShaderFXAA {
            get {
                return ResourceManager.GetString("ShaderFXAA", resourceCulture);
            }
        }
    }
}
